### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by Beliavsky** [grimme-lab/mctc-lib#20]
I'd like to add "Modular computation tool chain library" to the Fortran Code on GitHub list under Computational Chemistry but am unsure how to describe it in 1 or 2 sentences.

**Comment by awvwgk** [comment]
How about:

> Common tool chain to molecular structure data in various applications. This library provides a unified way to perform operations on molecular structure data, like reading and writing to common geometry file formats.

from the FORD documentation.

**Comment by Beliavsky** [comment]
Thanks. In the first sentence there should be a verb before "molecular", such as "use" or "access".
